### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [jackjyq/robbyrussell-plus-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by jackjyq** [comment]
Hi @unixorn , thanks for reaching out to me. I have added the screenshot and updated the readme file. Also, I am glad to be added to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list.

Regards,
Jack

**Comment by unixorn** [comment]
Thanks!
